server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  application:
    name: BarHub
  datasource:
    url: jdbc:mysql://127.0.0.1:33060/barhub
    username: juan
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      #ddl-auto: create
      #ddl-auto: update
      ddl-auto=create-drop
      #ddl-auto=none

    properties:
      hibernate:
        format_sql=true
  mail:
    host: smtp.gmail.com
    port: 587
    username: b4rhub01@gmail.com
    password: qvmc nihu lyum yfvk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
  logging:
    level:
      org.springframework: DEBUG

file:
  name: logs/app.log

jwt:
  jwtSecret: 123456789012345678901234567890%$   # Clave no en BASE 64 -> en Base 64 seria MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwJSQ=
  #jwtSecret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwJSQ=  # Clave en BASE 64
  #  jwtSecret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTA5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA5IzEl  # Clave en BASE 64
  jwtExpirationMs: 86400000