server:
  port: 8080

spring:
  application:
    name: BarHub
  datasource:
    url: jdbc:mysql://4.212.242.156:33060/barhub
    username: juan
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      #ddl-auto: update
      #ddl-auto=create-drop
      #ddl-auto=none

    properties:
      hibernate:
        format_sql=true

file:
  name: logs/app.log