server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

spring:
  application:
    name: BarHub
  config:
    import: optional:env.properties
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://mysql:3306/barhub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  logging:
    level:
      org.springframework: DEBUG

file:
  name: logs/app.log

jwt:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000