services:
  mysql:
  image: mysql:latest
  container_name: mysql
  restart: always
  ports:
    - 33060:3306
  networks:
    - mi_red
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${DB_DATABASE}
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
  volumes:
    - mysql_data:/var/lib/mysql

networks:
  mi_red:
    external: true

volumes:
  mysql_data: