services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=$(DUCKDNS_DOMAINS)
      - TOKEN=$(DUCKDNS_TOKEN)
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - /path/to/duckdns/config:/config
    restart: unless-stopped